### ISSUE TITLE
Case sensitive for object/member name

### ISSUE THREAD

**Issue by nonkit** [sb/smallbasic-editor#70] opened 2019-03-24 18:11 UTC
SBO v1.0 is case sensitive for object and member name.  Sample:
```
TextWindow.WriteLine("Pi=" + math.Pi)
```

**Comment by PieterBenjamin** [comment] 2019-03-28 01:24
I'm not sure why this is an issue - could you elaborate on what you believe the problem is?

**Comment by OmarTawfik** [comment] 2019-03-28 03:29
Do you think that we should be accepting `Math` and `math`?
Going forward, I think we should enforce it to teach students good practices. Most programming languages are case sensitive, and having `Math`, `math`, `MaTH`, etc... just decreases readability of your code.

**Comment by alxnull** [comment] 2019-03-28 12:41
@OmarTawfik While I understand your point of enforcing good practices I still think SB should be case-insensitive. This is quite common among BASIC dialects (e.g. Visual Basic .NET, which would be a possible language to learn after Small Basic) and it keeps compatibility with current SB Dektop versions.

**Comment by nonkit** [comment] 2019-03-31 06:53
I also reported this as parity issue.  SBD and SBO v0.91 are case insensitive.  And I'd like to comment that SBO v1.0 (this repo) is case insensitive for keywords such like If Then Else.

**Comment by nonkit** [comment] 2019-03-31 06:56
My understood why Small Basic Desktop is case insensitive is that being aware of case is little hard for beginners.  Especially for small children.

**Comment by OmarTawfik** [comment] 2019-04-02 07:12
I guess that makes sense. @EdPrice-MSFT please let us know if you have thoughts on the matter :)

**Comment by OmarTawfik** [comment] 2019-04-25 08:17
Thanks @nonkit for reporting. Fixed now.

**Comment by nonkit** [comment] 2019-05-08 16:03
I tried TextWindow.read().  It doesn't work correctly.  Something is wrong.

**Comment by OmarTawfik** [comment] 2019-05-14 05:48
@nonkit this is a different issue. I'll file #93 for that.

**Closed as completed by OmarTawfik** 2019-05-14 05:48 UTC
Labels: type/runtime, type/compiler
